// WooCommerce state/province data.
// Only countries with non-empty arrays require the `state` field, mirroring
// WooCommerce's own i18n/states.php for this store's allowed countries.
// Verified against this store's live WooCommerce instance (wp-admin order form).

export interface StateOption {
  code: string;
  name: string;
}

export const COUNTRY_STATES: Record<string, StateOption[]> = {
  ES: [
    { code: 'VI', name: 'Araba/Álava' },
    { code: 'AB', name: 'Albacete' },
    { code: 'A', name: 'Alicante' },
    { code: 'AL', name: 'Almería' },
    { code: 'O', name: 'Asturias' },
    { code: 'AV', name: 'Ávila' },
    { code: 'BA', name: 'Badajoz' },
    { code: 'PM', name: 'Baleares' },
    { code: 'B', name: 'Barcelona' },
    { code: 'BU', name: 'Burgos' },
    { code: 'CC', name: 'Cáceres' },
    { code: 'CA', name: 'Cádiz' },
    { code: 'S', name: 'Cantabria' },
    { code: 'CS', name: 'Castellón' },
    { code: 'CE', name: 'Ceuta' },
    { code: 'CR', name: 'Ciudad Real' },
    { code: 'CO', name: 'Córdoba' },
    { code: 'CU', name: 'Cuenca' },
    { code: 'GI', name: 'Girona' },
    { code: 'GR', name: 'Granada' },
    { code: 'GU', name: 'Guadalajara' },
    { code: 'SS', name: 'Gipuzkoa' },
    { code: 'H', name: 'Huelva' },
    { code: 'HU', name: 'Huesca' },
    { code: 'J', name: 'Jaén' },
    { code: 'LO', name: 'La Rioja' },
    { code: 'GC', name: 'Las Palmas' },
    { code: 'LE', name: 'León' },
    { code: 'L', name: 'Lleida' },
    { code: 'LU', name: 'Lugo' },
    { code: 'M', name: 'Madrid' },
    { code: 'MA', name: 'Málaga' },
    { code: 'ML', name: 'Melilla' },
    { code: 'MU', name: 'Murcia' },
    { code: 'NA', name: 'Navarra' },
    { code: 'OR', name: 'Ourense' },
    { code: 'P', name: 'Palencia' },
    { code: 'PO', name: 'Pontevedra' },
    { code: 'SA', name: 'Salamanca' },
    { code: 'TF', name: 'Santa Cruz de Tenerife' },
    { code: 'SG', name: 'Segovia' },
    { code: 'SE', name: 'Sevilla' },
    { code: 'SO', name: 'Soria' },
    { code: 'T', name: 'Tarragona' },
    { code: 'TE', name: 'Teruel' },
    { code: 'TO', name: 'Toledo' },
    { code: 'V', name: 'Valencia' },
    { code: 'VA', name: 'Valladolid' },
    { code: 'BI', name: 'Biscay' },
    { code: 'ZA', name: 'Zamora' },
    { code: 'Z', name: 'Zaragoza' },
  ],
  IT: [
    { code: 'AG', name: 'Agrigento' },
    { code: 'AL', name: 'Alessandria' },
    { code: 'AN', name: 'Ancona' },
    { code: 'AO', name: 'Aosta' },
    { code: 'AR', name: 'Arezzo' },
    { code: 'AP', name: 'Ascoli Piceno' },
    { code: 'AT', name: 'Asti' },
    { code: 'AV', name: 'Avellino' },
    { code: 'BA', name: 'Bari' },
    { code: 'BT', name: 'Barletta-Andria-Trani' },
    { code: 'BL', name: 'Belluno' },
    { code: 'BN', name: 'Benevento' },
    { code: 'BG', name: 'Bergamo' },
    { code: 'BI', name: 'Biella' },
    { code: 'BO', name: 'Bologna' },
    { code: 'BZ', name: 'Bolzano' },
    { code: 'BS', name: 'Brescia' },
    { code: 'BR', name: 'Brindisi' },
    { code: 'CA', name: 'Cagliari' },
    { code: 'CL', name: 'Caltanissetta' },
    { code: 'CB', name: 'Campobasso' },
    { code: 'CE', name: 'Caserta' },
    { code: 'CT', name: 'Catania' },
    { code: 'CZ', name: 'Catanzaro' },
    { code: 'CH', name: 'Chieti' },
    { code: 'CO', name: 'Como' },
    { code: 'CS', name: 'Cosenza' },
    { code: 'CR', name: 'Cremona' },
    { code: 'KR', name: 'Crotone' },
    { code: 'CN', name: 'Cuneo' },
    { code: 'EN', name: 'Enna' },
    { code: 'FM', name: 'Fermo' },
    { code: 'FE', name: 'Ferrara' },
    { code: 'FI', name: 'Firenze' },
    { code: 'FG', name: 'Foggia' },
    { code: 'FC', name: 'Forlì-Cesena' },
    { code: 'FR', name: 'Frosinone' },
    { code: 'GE', name: 'Genova' },
    { code: 'GO', name: 'Gorizia' },
    { code: 'GR', name: 'Grosseto' },
    { code: 'IM', name: 'Imperia' },
    { code: 'IS', name: 'Isernia' },
    { code: 'SP', name: 'La Spezia' },
    { code: 'AQ', name: "L'Aquila" },
    { code: 'LT', name: 'Latina' },
    { code: 'LE', name: 'Lecce' },
    { code: 'LC', name: 'Lecco' },
    { code: 'LI', name: 'Livorno' },
    { code: 'LO', name: 'Lodi' },
    { code: 'LU', name: 'Lucca' },
    { code: 'MC', name: 'Macerata' },
    { code: 'MN', name: 'Mantova' },
    { code: 'MS', name: 'Massa-Carrara' },
    { code: 'MT', name: 'Matera' },
    { code: 'ME', name: 'Messina' },
    { code: 'MI', name: 'Milano' },
    { code: 'MO', name: 'Modena' },
    { code: 'MB', name: 'Monza e della Brianza' },
    { code: 'NA', name: 'Napoli' },
    { code: 'NO', name: 'Novara' },
    { code: 'NU', name: 'Nuoro' },
    { code: 'OR', name: 'Oristano' },
    { code: 'PD', name: 'Padova' },
    { code: 'PA', name: 'Palermo' },
    { code: 'PR', name: 'Parma' },
    { code: 'PV', name: 'Pavia' },
    { code: 'PG', name: 'Perugia' },
    { code: 'PU', name: 'Pesaro e Urbino' },
    { code: 'PE', name: 'Pescara' },
    { code: 'PC', name: 'Piacenza' },
    { code: 'PI', name: 'Pisa' },
    { code: 'PT', name: 'Pistoia' },
    { code: 'PN', name: 'Pordenone' },
    { code: 'PZ', name: 'Potenza' },
    { code: 'PO', name: 'Prato' },
    { code: 'RG', name: 'Ragusa' },
    { code: 'RA', name: 'Ravenna' },
    { code: 'RC', name: 'Reggio Calabria' },
    { code: 'RE', name: 'Reggio Emilia' },
    { code: 'RI', name: 'Rieti' },
    { code: 'RN', name: 'Rimini' },
    { code: 'RM', name: 'Roma' },
    { code: 'RO', name: 'Rovigo' },
    { code: 'SA', name: 'Salerno' },
    { code: 'SS', name: 'Sassari' },
    { code: 'SV', name: 'Savona' },
    { code: 'SI', name: 'Siena' },
    { code: 'SR', name: 'Siracusa' },
    { code: 'SO', name: 'Sondrio' },
    { code: 'SU', name: 'Sud Sardegna' },
    { code: 'TA', name: 'Taranto' },
    { code: 'TE', name: 'Teramo' },
    { code: 'TR', name: 'Terni' },
    { code: 'TO', name: 'Torino' },
    { code: 'TP', name: 'Trapani' },
    { code: 'TN', name: 'Trento' },
    { code: 'TV', name: 'Treviso' },
    { code: 'TS', name: 'Trieste' },
    { code: 'UD', name: 'Udine' },
    { code: 'VA', name: 'Varese' },
    { code: 'VE', name: 'Venezia' },
    { code: 'VB', name: 'Verbano-Cusio-Ossola' },
    { code: 'VC', name: 'Vercelli' },
    { code: 'VR', name: 'Verona' },
    { code: 'VV', name: 'Vibo Valentia' },
    { code: 'VI', name: 'Vicenza' },
    { code: 'VT', name: 'Viterbo' },
  ],
  DE: [
    { code: 'DE-BW', name: 'Baden-Württemberg' },
    { code: 'DE-BY', name: 'Bavaria' },
    { code: 'DE-BE', name: 'Berlin' },
    { code: 'DE-BB', name: 'Brandenburg' },
    { code: 'DE-HB', name: 'Bremen' },
    { code: 'DE-HH', name: 'Hamburg' },
    { code: 'DE-HE', name: 'Hesse' },
    { code: 'DE-MV', name: 'Mecklenburg-Vorpommern' },
    { code: 'DE-NI', name: 'Lower Saxony' },
    { code: 'DE-NW', name: 'North Rhine-Westphalia' },
    { code: 'DE-RP', name: 'Rhineland-Palatinate' },
    { code: 'DE-SL', name: 'Saarland' },
    { code: 'DE-SN', name: 'Saxony' },
    { code: 'DE-ST', name: 'Saxony-Anhalt' },
    { code: 'DE-SH', name: 'Schleswig-Holstein' },
    { code: 'DE-TH', name: 'Thuringia' },
  ],
  // FR, GB, PL: no states in this store's WooCommerce instance.
};

export const countryRequiresState = (countryCode: string): boolean =>
  Boolean(COUNTRY_STATES[countryCode]?.length);

export const getStatesForCountry = (countryCode: string): StateOption[] =>
  COUNTRY_STATES[countryCode] ?? [];
